openapi: 3.0.1
info:
  title: Authentication API
  description: API for user authentication and registration
  version: 1.0.0
paths:
  /api/login.php:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                authentication_provider:
                  type: string
                  enum: [USERNAME_PASSWORD, GOOGLE]
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user_id:
                    type: string
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: Invalid credentials or authentication provider
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/register.php:
    post:
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                authentication_provider:
                  type: string
                  enum: [USERNAME_PASSWORD, GOOGLE]
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user_id:
                    type: string
        '400':
          description: Invalid input or duplicate entry
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
