services:
  database:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
  app:
    image: 'httpd:2.4'
    restart: always
    ports:
        - '80:80'
    volumes:
        - './frontend:/usr/local/apache2/htdocs/'